<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <Title>NSHub.ServiceDefaults</Title>
      <Product>NSHub.ServiceDefaults</Product>
      <Description>NSHub.ServiceDefaults</Description>
      <PackageId>NSHub.ServiceDefaults</PackageId>
      <RootNamespace>NSHub.ServiceDefaults</RootNamespace>
      <AssemblyName>NSHub.ServiceDefaults</AssemblyName>
    <IsAspireSharedProject>true</IsAspireSharedProject>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.10.0" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="10.10.0" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.19.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.19.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.19.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.19.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.19.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.CodeAnalysis.NetAnalyzers" Version="11.0.100-rc.1.26425.128" />
  </ItemGroup>

</Project>
