<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Title>PlanetHub.Models</Title>
        <Product>PlanetHub.Models</Product>
        <Description>PlanetHub.Models</Description>
        <PackageId>PlanetHub.Models</PackageId>
        <RootNamespace>PlanetHub.Models</RootNamespace>
        <AssemblyName>PlanetHub.Models</AssemblyName>
        <namespace>PlanetHub.Models</namespace>

    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="PlanetHub.Cryptographies" Version="2025.12.29.15" />
        <PackageReference Include="PlanetHub.Enums" Version="2025.12.29.18" />
        <PackageReference Include="PlanetHub.Localization" Version="2025.12.21.13" />
        <ProjectReference Include="..\PlanetHub.Localization\PlanetHub.Localization.csproj" />
        <PackageReference Update="SonarAnalyzer.CSharp" Version="10.17.0.131074" />
        <PackageReference Update="Roslynator.Core" Version="4.15.0" />
        <PackageReference Update="Microsoft.CodeAnalysis" Version="5.0.0" />
        <PackageReference Update="Roslynator.Analyzers" Version="4.15.0" />
        <PackageReference Update="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="5.0.0" />
        <PackageReference Update="Microsoft.CodeAnalysis.Workspaces.Common" Version="5.0.0" />
    </ItemGroup>

</Project>