<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>NSHub.Domain</Title>
    <Product>NSHub.Domain</Product>
    <Description>NSHub.Domain</Description>
    <PackageId>NSHub.Domain</PackageId>
    <RootNamespace>NSHub.Domain</RootNamespace>
    <AssemblyName>NSHub.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
     <PackageReference
                Include="MailKit"
                Version="4.16.0" />
				<PackageReference
        Update="Microsoft.CodeAnalysis.NetAnalyzers"
        Version="11.0.100-rc.1.26425.128" />
    <PackageReference
        Update="Roslynator.Analyzers"
        Version="5.0.0" />
    <PackageReference
        Update="Roslynator.CodeFixes"
        Version="5.0.0" />
  </ItemGroup>

</Project>
