<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>NSHub.Infrastructure</Title>
    <Product>NSHub.Infrastructure</Product>
    <Description>NSHub.Infrastructure</Description>
    <PackageId>NSHub.Infrastructure</PackageId>
    <RootNamespace>NSHub.Infrastructure</RootNamespace>
    <AssemblyName>NSHub.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NSHub.Application\NSHub.Application.csproj" />
    <ProjectReference Include="..\NSHub.Domain\NSHub.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Repositories\**" />
    <None Remove="Repositories\**" />
    <Compile Remove="Pdfs\**" />
    <None Remove="Pdfs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="11.0.0-rc.1.26425.128">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="11.0.0-rc.1.26425.128">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.1" />
    <PackageReference Include="SqlKata" Version="4.0.1" />
    <PackageReference Include="QuestPDF" Version="2025.12.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference
        Update="Microsoft.CodeAnalysis.NetAnalyzers"
        Version="11.0.100-rc.1.26425.128" />
    <PackageReference
        Update="Roslynator.Analyzers"
        Version="5.0.0" />
    <PackageReference
        Update="Roslynator.CodeFixes"
        Version="5.0.0" />
  </ItemGroup>

</Project>
