// <copyright file="ValidationException.cs" company="Davide Nava">
// Copyright (c) Davide Nava. All rights reserved.
// </copyright>

using FluentValidation.Results;

namespace NSHub.Application.Common.Exceptions;

/// <summary>
/// Represents an exception that is thrown when one or more validation failures occur.
/// </summary>
public class ValidationException : Exception
{
    /// <summary>
    /// Gets the validation errors grouped by property name.
    /// </summary>
    public IDictionary<string, string[]> Errors { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="ValidationException"/> class.
    /// </summary>
    public ValidationException()
        : base("One or more validation failures have occurred.") => Errors = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase);

    /// <summary>
    /// Initializes a new instance of the <see cref="ValidationException"/> class
    /// with validation errors grouped by property name.
    /// </summary>
    /// <param name="failures">
    /// The collection of validation failures generated by FluentValidation.
    /// </param>
    public ValidationException(IEnumerable<ValidationFailure> failures)
        : this()
    {
        Errors = failures
            .GroupBy(e => e.PropertyName, e => e.ErrorMessage, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(
                failureGroup => failureGroup.Key,
                failureGroup => failureGroup.ToArray(), StringComparer.OrdinalIgnoreCase);
    }
}
